export interface SearchCategory {
    id: string;
    name: string;
    hashtag: string;
}

export const searchCategories: SearchCategory[] = [
    { id: '1', name: 'musik', hashtag: '#musik' },
    { id: '2', name: 'gaming', hashtag: '#gaming' },
    { id: '3', name: 'film', hashtag: '#film' },
    { id: '4', name: 'makanan', hashtag: '#makanan' },
    { id: '5', name: 'anime', hashtag: '#anime' },
    { id: '6', name: 'meme', hashtag: '#meme' },
    { id: '7', name: 'olahraga', hashtag: '#olahraga' },
    { id: '8', name: 'teknologi', hashtag: '#teknologi' },
    { id: '9', name: 'seni', hashtag: '#seni' },
    { id: '10', name: 'binatang', hashtag: '#binatang' },
    { id: '11', name: 'buku', hashtag: '#buku' },
    { id: '12', name: 'riwayat', hashtag: '#riwayat' },
    { id: '13', name: 'budaya', hashtag: '#budaya' },
    { id: '14', name: 'sains', hashtag: '#sains' },
    { id: '15', name: 'video', hashtag: '#video' },
    { id: '16', name: 'bahasa', hashtag: '#bahasa' },
    { id: '17', name: 'filosofi', hashtag: '#filosofi' },
    { id: '18', name: 'nasihathubungan', hashtag: '#nasihathubungan' },
    { id: '19', name: 'fitness', hashtag: '#fitness' },
    { id: '20', name: 'negara', hashtag: '#negara' },
    { id: '21', name: 'fashion', hashtag: '#fashion' },
    { id: '22', name: 'televisi', hashtag: '#televisi' },
    { id: '23', name: 'seks', hashtag: '#seks' },
    { id: '24', name: 'berita', hashtag: '#berita' },
    { id: '25', name: 'kerja', hashtag: '#kerja' },
    { id: '26', name: 'kesehatan', hashtag: '#kesehatan' },
    { id: '27', name: 'belanja', hashtag: '#belanja' },
    { id: '28', name: 'agama', hashtag: '#agama' },
    { id: '29', name: 'kepribadian', hashtag: '#kepribadian' },
    { id: '30', name: 'keuangan', hashtag: '#keuangan' },
    { id: '31', name: 'rumah', hashtag: '#rumah' },
];

export const searchCategoriesEnglish: SearchCategory[] = [
    { id: '1', name: 'music', hashtag: '#music' },
    { id: '2', name: 'gaming', hashtag: '#gaming' },
    { id: '3', name: 'film', hashtag: '#film' },
    { id: '4', name: 'food', hashtag: '#food' },
    { id: '5', name: 'anime', hashtag: '#anime' },
    { id: '6', name: 'meme', hashtag: '#meme' },
    { id: '7', name: 'sports', hashtag: '#sports' },
    { id: '8', name: 'technology', hashtag: '#technology' },
    { id: '9', name: 'art', hashtag: '#art' },
    { id: '10', name: 'animals', hashtag: '#animals' },
    { id: '11', name: 'books', hashtag: '#books' },
    { id: '12', name: 'history', hashtag: '#history' },
    { id: '13', name: 'culture', hashtag: '#culture' },
    { id: '14', name: 'science', hashtag: '#science' },
    { id: '15', name: 'video', hashtag: '#video' },
    { id: '16', name: 'language', hashtag: '#language' },
    { id: '17', name: 'philosophy', hashtag: '#philosophy' },
    { id: '18', name: 'relationshipadvice', hashtag: '#relationshipadvice' },
    { id: '19', name: 'fitness', hashtag: '#fitness' },
    { id: '20', name: 'country', hashtag: '#country' },
    { id: '21', name: 'fashion', hashtag: '#fashion' },
    { id: '22', name: 'television', hashtag: '#television' },
    { id: '23', name: 'sex', hashtag: '#sex' },
    { id: '24', name: 'news', hashtag: '#news' },
    { id: '25', name: 'work', hashtag: '#work' },
    { id: '26', name: 'health', hashtag: '#health' },
    { id: '27', name: 'shopping', hashtag: '#shopping' },
    { id: '28', name: 'religion', hashtag: '#religion' },
    { id: '29', name: 'personality', hashtag: '#personality' },
    { id: '30', name: 'finance', hashtag: '#finance' },
    { id: '31', name: 'home', hashtag: '#home' },
];
